services:

  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
    ports:
      - "8200:3000"
      - "8300:3001"
    shm_size: "1gb" 
    restart: unless-stopped

    
